name: incubator
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0-279.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  flutter_bloc:
  smooth_page_indicator:
  flutter_svg: ^2.0.10+1
  pinput: ^4.0.0
  curved_navigation_bar: ^1.0.3
  percent_indicator: ^4.2.3
  # flutter_native_splash: ^2.4.0

# flutter_native_splash:
#   color: "#F59E0B"
#   image: assets/images/logo.png
#   android: true
#   ios: true


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
